# package manager
alias install='sudo apt install'
alias update='sudo apt update'
alias upgrade='sudo apt update && sudo apt upgrade -y'
alias show='apt-cache show'
alias search='apt-cache search'
alias autoremove='sudo apt autoremove --purge'

# symfony
alias sy='php bin/console'
alias sy_dbupdate='sy doctrine:schema:update'
alias sy_ge='sy doctrine:generate:entity'
alias sy_gf='sy doctrine:generate:form'
alias sy_ges='sy doctrine:generate:entities'
alias sy_clearp='sy cache:clear --no-warmup --env=prod'
alias sy_cleard='sy cache:clear --no-warmup --env=dev'
alias sy_load_fixt='sy doctrine:fixtures:load'
alias sy_gen_assets='sy_clearp && sy_cleard && sy assetic:dump --no-debug --env=prod'

# divers
alias gdb='gdb -q'
alias octave-cli='octave-cli -q'
alias go='gnome-open'
alias taille='du -hs'
alias ccat='pygmentize -g'
alias ppath='echo $PATH | tr ":" "\n"'
alias pip_upgrade='sudo pip list --outdated --format=freeze 2> /dev/null | cut -d= -f1 | xargs sudo pip install -U'

# server
alias occ='sudo -u www-data php /var/www/nextcloud/occ'

# dev
alias catkin_maked='catkin_make -DCMAKE_BUILD_TYPE=Debug'
alias catkin_maket='catkin_make -DCMAKE_BUILD_TYPE=Debug run_tests_mario'
alias catkin_make='catkin_make  -DCMAKE_BUILD_TYPE=Release'
alias rrd='rosrun --prefix "gdb -q run --args"'
alias rrv='rosrun --prefix "valgrind --leak-check=full"'
