# package manager
alias install='sudo apt install'
alias update='sudo apt update'
alias upgrade='sudo apt update && sudo apt upgrade -y'
alias show='apt-cache show'
alias search='apt-cache search'
alias autoremove='sudo apt autoremove --purge'

# symfony
alias sy='php bin/console'
alias sy_dbupdate='sy doctrine:schema:update'
alias sy_ge='sy doctrine:generate:entity'
alias sy_gf='sy doctrine:generate:form'
alias sy_ges='sy doctrine:generate:entities'
alias sy_clearp='sy cache:clear --env=prod'
alias sy_cleard='sy cache:clear --env=dev'

# divers
alias gdb='gdb -q'
alias go='gnome-open'
alias taille='du -hs'
alias ccat='pygmentize -g'

# dev
alias catkin_maked='catkin_make -DCMAKE_BUILD_TYPE=Debug'
alias catkin_maket='catkin_make -DCMAKE_BUILD_TYPE=Debug run_tests_mario'
alias catkin_make='catkin_make  -DCMAKE_BUILD_TYPE=Release'
alias rrd='rosrun --prefix "gdb -q run --args"'
alias rrv='rosrun --prefix "valgrind --leak-check=full"'
