# Basic bash aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# package manager
alias install='sudo apt install'
alias update='sudo apt update'
alias upgrade='sudo apt update && sudo apt upgrade -y'
alias show='apt-cache show'
alias search='apt-cache search'
alias autoremove='sudo apt autoremove --purge'

# symfony
alias sy='php bin/console'
alias sy_updatedb='sy doctrine:schema:update'
alias sy_ge='sy doctrine:generate:entity'
alias sy_ges='sy doctrine:generate:entities'
alias sy_gf='sy doctrine:generate:form'
alias sy_clearp='sy cache:clear --no-warmup --env=prod'
alias sy_cleard='sy cache:clear --no-warmup --env=dev'
alias sy_load_fixt='sy doctrine:fixtures:load'
alias sy_gen_assets='sy_clearp && sy_cleard && sy assetic:dump --no-debug --env=prod'

# flask
function fl_run {
    export FLASK_ENV=development
    export FLASK_APP="$1"
    flask run
}

# divers
alias gdb='gdb -q'
alias octave-cli='octave-cli -q'
alias go='xdg-open'
alias taille='du -hs'
alias ccat='pygmentize -g'
alias ppath='echo $PATH | tr ":" "\n"'
alias pip_upgrade='sudo pip list --outdated --format=freeze 2> /dev/null | cut -d= -f1 | xargs sudo pip install -U'
alias my_alert='notify-send --urgency=low \
                            -i "$([ $? = 0 ] && echo terminal || echo error)" \
                            "$(history|tail -n2|head -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"; \
                paplay /usr/share/sounds/ubuntu/stereo/message.ogg'
alias check_boot='[ -d /sys/firmware/efi ] && echo UEFI || echo BIOS'
alias publicip='curl ipinfo.io/ip'
alias sync_music="rsync -arv paul-mesnilgrente.com:/home/Music/ $HOME/Music"

# my python scripts
alias mangadownloader.py='$HOME/.pyenv/versions/3.7.5/envs/mangadownloader/bin/python3 $HOME/bin/mangadownloader.py'

# server
alias occ='sudo -u www-data php /var/www/nextcloud/occ'
