filetype off " required
execute pathogen#infect()

"All of your Plugins must be added before the following line
filetype plugin indent on

set backspace=indent,eol,start
syntax enable      " color syntaxing
set number         " print numbers on the side of the window
set paste          " paste properly in insert mode
set mouse=a        " enable the use of mouse for every mode
set hlsearch       " highlight all matches when search
set showmatch      " show the match (,{ etc.
set splitbelow     " when using :sp insert the new file below
set splitright     " when using :vsp insert the new file right
set tabstop=4      " show existing tab with 4 spaces width
set shiftwidth=4   " when indenting with >, use 4 spaces width
set expandtab      " On pressing tab, insert 4 spaces
set autowrite      " save when you change of window or tab
au FocusLost * :wa " save when focus is lost

" POWERLINE
set rtp+=/usr/local/lib/python3.6/dist-packages/powerline/bindings/vim/
set laststatus=2
set t_Co=256

" COLOR SCHEMES : https://github.com/flazz/vim-colorschemes
colorscheme Monokai

" MARKDOWN Highlighting : https://github.com/plasticboy/vim-markdown
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_math = 1

" MARKDOWN PREVIEW : https://github.com/JamshedVesuna/vim-markdown-preview
let vim_markdown_preview_github=1 " github renderer (need internet access)

" CPP HIGHLIGHTING : https://github.com/octol/vim-cpp-enhanced-highlight
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_concepts_highlight = 1

" SYNTASTIC : https://github.com/vim-syntastic/syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
